#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
##############################################################################

if [ "$#" -gt 0 ]; then
    APP_NAME="$0"
    DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'
    APP_HOME=$( cd "${0%[/\\]*}" > /dev/null && pwd -P ) || exit

    # Add default JVM options here.
    if [ -z "$JAVA_HOME" ]; then
        JAVACMD=$( which java 2>/dev/null ) || {
            echo "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
            exit 1
        }
    else
        JAVACMD="$JAVA_HOME/bin/java"
    fi

    CLASSPATH="$APP_HOME/gradle/wrapper/gradle-wrapper.jar"
    exec "$JAVACMD" $DEFAULT_JVM_OPTS $JAVA_OPTS $GRADLE_OPTS \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain "$@"
fi
